### PR TITLE
Observatories

### PR DESCRIPTION
**Pull request by rcooke-ast**
Added functionality to run tests for all instruments of a given observatory.

### CODE REVIEW

**Comment by profxj** [comment]
Looks fine, but I assume it needs PR #282 in PYPIT to clear.

Merge after it does.

**Comment by profxj** [comment]
Am crashing out on ISIS on the triangles branch of arclines
and the hires_optimal branch of PYPIT.

Thoughts @rcooke-ast ?

Here is a snippet of the apparent Cython failure:

  File "/home/xavier/local/Python/PYPIT/pypit/arwave.py", line 296, in flexure_obj
    fdict = flex_shift(slf, det, obj_sky, arx_sky)
  File "/home/xavier/local/Python/PYPIT/pypit/arwave.py", line 40, in flex_shift
    arx_amp, arx_cent, arx_wid, arx_w, arx_satsnd, arx_yprep = ararc.detect_lines(slf, det, msarc=None, censpec=arx_skyspec.flux.value, MK_SATMASK=False)
  File "/home/xavier/local/Python/PYPIT/pypit/ararc.py", line 100, in detect_lines
    tampl, tcent, twid, ngood = arcyarc.fit_arcorder(xrng, detns, pixt, fitp)
  File "pypit/arcyarc.pyx", line 40, in pypit.arcyarc.fit_arcorder
ValueError: Buffer dtype mismatch, expected 'DTYPE_t' but got 'float'

Got this after crashing on pypit_test and so ran the code manually:

wolverine> pwd
/home/xavier/local/Python/PYPIT-development-suite/REDUX_OUT/WHT_ISIS_blue/long_R300B_d5300
wolverine> run_pypit -d wht_isis_blue_long_r300b_d5300.pypit

**Comment by rcooke-ast** [comment]
I'm not crashing on this. Maybe check that you've compiled the cython code (i.e. `python setup.py develop`). I've also pushed a commit which might address the issue explicitly, by forcing the type definition of the arrays.

I'm sure this fuels your passion to remove cython code from PYPIT... me too!    ;-)

**Comment by rcooke-ast** [comment]
OK - I've removed the cython code and replaced it with a variation (but in python). The result is a better centroiding on the arc lines (i.e. lower pixel RMS in the arc fit) and not too significant a slow down. About to push the commits to the PYPIT branch now.

**Comment by profxj** [comment]
Suite failed for me on hires_uv but I'm assuming that was expected.

Right @rcooke-ast ?

**Comment by profxj** [comment]
Ah, I see now that I need to add CuI to arclines.

@rcooke-ast -- merge this if you think it is ok I failed on hires_uv

**Comment by rcooke-ast** [comment]
I don't get a fail for hires_uv. I get a fail for ISIS, I've just realized that I get a fail for ISIS, but I'll fix this with the latest PR of PYPIT. stay tuned. For the moment, I think the development suite can be safely merged (the problem is with PYPIT, not the dev suite).

**Pull request merged**
